import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../../components/ui/card';
import { FileText, Search, Filter, Sparkles, Download, Mic, User } from 'lucide-react';
import { Input } from '../../components/ui/input';
import { Button } from '../../components/ui/button';
import { toast } from 'sonner';
import { Dialog } from '../../components/ui/dialog';

export default function SoapNotes() {
  const notes = [
    { id: 1, date: 'Oct 12, 2023', patient: 'Alex Johnson', author: 'AI Scribe', diagnosis: 'Atypical Chest Pain', status: 'Signed' },
    { id: 2, date: 'Oct 10, 2023', patient: 'Maria Garcia', author: 'Dr. Smith', diagnosis: 'Type 2 Diabetes', status: 'Draft' },
    { id: 3, date: 'Oct 05, 2023', patient: 'James Wilson', author: 'AI Scribe', diagnosis: 'Hypertension', status: 'Signed' },
  ];

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedNote, setSelectedNote] = useState<typeof notes[0] | null>(null);

  return (
    <div className="p-8 h-full flex flex-col bg-muted/10 overflow-y-auto">
      <div className="mb-8 flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold flex items-center gap-3 mb-2">
            <FileText className="w-8 h-8 text-emerald-500" />
            SOAP Notes & Documentation
          </h1>
          <p className="text-muted-foreground">AI-assisted clinical documentation and historical records.</p>
        </div>
        <Button className="bg-emerald-600 hover:bg-emerald-700 gap-2" onClick={() => toast.success('Starting AI Scribe...', { description: 'Microphone access requested.' })}>
          <Mic className="w-4 h-4" /> AI Scribe Note
        </Button>
      </div>

      <div className="flex gap-4 mb-6">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input placeholder="Search by patient, diagnosis, or keyword..." className="pl-9" />
        </div>
        <Button variant="outline" className="gap-2"><Filter className="w-4 h-4" /> Filter</Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {notes.map((note, idx) => (
          <Card key={idx} className="hover:border-emerald-500/50 transition-colors cursor-pointer group flex flex-col">
            <CardHeader className="pb-3 border-b bg-muted/20">
              <div className="flex justify-between items-start mb-2">
                <span className="text-xs font-semibold text-muted-foreground">{note.date}</span>
                <span className={`text-[10px] font-bold uppercase px-2 py-1 rounded ${note.status === 'Signed' ? 'bg-emerald-500/10 text-emerald-600' : 'bg-amber-500/10 text-amber-600'}`}>
                  {note.status}
                </span>
              </div>
              <CardTitle className="text-lg">{note.patient}</CardTitle>
              <CardDescription>{note.diagnosis}</CardDescription>
            </CardHeader>
            <CardContent className="pt-4 flex-1 flex flex-col justify-between">
              <div className="space-y-2 mb-6">
                <p className="text-xs text-muted-foreground flex items-center gap-1">
                  <span className="font-semibold text-foreground">Generated by:</span>
                  {note.author === 'AI Scribe' ? <span className="flex items-center gap-1 text-emerald-500"><Sparkles className="w-3 h-3" /> etoh AI</span> : note.author}
                </p>
                <div className="text-sm text-muted-foreground line-clamp-3 p-3 bg-muted/50 rounded-lg">
                  <strong>S:</strong> Patient reports...<br />
                  <strong>O:</strong> Vitals stable...<br />
                  <strong>A:</strong> Follow-up...
                </div>
              </div>
              <div className="flex justify-between items-center mt-6 pt-4 border-t">
                <Button variant="ghost" className="text-primary hover:text-primary hover:bg-primary/10 gap-2" onClick={() => { setSelectedNote(note); setIsModalOpen(true); }}>
                  View Full Note
                </Button>
                <Button variant="ghost" size="icon" onClick={() => toast.success(`Downloaded note for ${note.patient}`)}>
                  <Download className="w-4 h-4 text-muted-foreground" />
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <Dialog isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title={`SOAP Note: ${selectedNote?.patient}`} description={`Date: ${selectedNote?.date} • Diagnosis: ${selectedNote?.diagnosis}`} maxWidth="2xl">
        {selectedNote && (
          <div className="space-y-6 text-sm">
            <div className="flex items-center gap-4 bg-muted/30 p-4 rounded-xl border">
              <div className="w-12 h-12 rounded-full bg-emerald-500/10 flex items-center justify-center">
                <User className="w-6 h-6 text-emerald-600" />
              </div>
              <div className="flex-1">
                <p className="font-bold">{selectedNote.patient}</p>
                <p className="text-xs text-muted-foreground">DOB: 05/12/1980 (43 yrs) • MRN: 9821-442</p>
              </div>
              <div className="text-right">
                <p className="text-xs font-bold text-muted-foreground">STATUS</p>
                <p className={`font-bold ${selectedNote.status === 'Signed' ? 'text-emerald-500' : 'text-amber-500'}`}>{selectedNote.status}</p>
              </div>
            </div>

            <div className="space-y-4">
              <div>
                <h3 className="font-bold text-lg mb-2 text-foreground border-b pb-1">Subjective</h3>
                <p className="text-muted-foreground leading-relaxed">Patient presents with a 3-day history of intermittent, sharp chest pain, worse on exertion. Denies shortness of breath, nausea, or diaphoresis. States they have been under significant stress at work. No prior history of similar symptoms.</p>
              </div>

              <div>
                <h3 className="font-bold text-lg mb-2 text-foreground border-b pb-1">Objective</h3>
                <p className="text-muted-foreground leading-relaxed">Vitals: BP 120/80, HR 78, RR 16, SpO2 99% on RA, Temp 98.6°F.<br />Gen: Alert, oriented, no acute distress.<br />CV: Regular rate and rhythm, normal S1/S2, no murmurs, rubs, or gallops.<br />Resp: Clear to auscultation bilaterally, no wheezes or crackles.<br />Tests: ECG shows normal sinus rhythm. Troponin pending.</p>
              </div>

              <div>
                <h3 className="font-bold text-lg mb-2 text-foreground border-b pb-1">Assessment</h3>
                <p className="text-muted-foreground leading-relaxed">1. Atypical chest pain: Likely musculoskeletal or stress-related given normal ECG and stable vitals. Low suspicion for acute coronary syndrome.<br />2. Generalized Anxiety/Stress: Contributory to presentation.</p>
              </div>

              <div>
                <h3 className="font-bold text-lg mb-2 text-foreground border-b pb-1">Plan</h3>
                <p className="text-muted-foreground leading-relaxed">- Prescribe Naproxen 500mg PRN for pain.<br />- Recommend stress management techniques and follow up with PCP in 2 weeks.<br />- Await troponin results; if negative, safe for discharge.<br />- Strict return precautions provided.</p>
              </div>
            </div>

            <div className="pt-4 border-t flex justify-end gap-2">
              <Button variant="outline" onClick={() => setIsModalOpen(false)}>Close</Button>
              <Button className="bg-emerald-500 hover:bg-emerald-600 gap-2"><Download className="w-4 h-4" /> Export PDF</Button>
            </div>
          </div>
        )}
      </Dialog>
    </div>
  );
}
